services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=pedidos'
      - 'MONGO_INITDB_ROOT_PASSWORD=pedido'
      - 'MONGO_INITDB_ROOT_USERNAME=btg'
    ports:
      - '27017'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=pedido'
      - 'RABBITMQ_DEFAULT_USER=btg'
    ports:
      - '5672'
#      - '15672:15672'
